#version: '3.10'
#
#services:
#  docMySQL:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: a?xBVq1!
#      MYSQL_DATABASE: RawData
#    volumes:
#      - mysql-data:/var/lib/mysql
#    ports:
#    -  "3306:3306"
#
#app:
#    build: .
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#volumes:
#  mysql-data:

version: '3.10'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: a?xBVq1!
      MYSQL_DATABASE: RawData
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    image: data-streaming-app  # Use the Docker image we built
    build:
      context: .               # Use the current directory as the build context
      dockerfile: Docker # Specify the Dockerfile if needed
    volumes:
      - .:/code                # Mount the current directory into the container
    depends_on:
      - db                     # Ensure the app starts after the MySQL service
    networks:
      - app-network
    environment:
      - DATABASE_HOST=db       # Environment variable for database connection
      - DATABASE_PORT=3306     # Port for the database
      - DATABASE_NAME=RawData  # Database name
      - DATABASE_USER=root     # Database user
      - DATABASE_PASSWORD=a?xBVq1! # Database password

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
