@startuml
allowmixing
title MYSQLDataProcessor Class Structure and Workflow

package "Scripts and Configs" {
    component [main.py]
    component [config.json]
    component [init_db.sh]
}

class MYSQLDataProcessor {
    -SparkSession: spark
    -String: jdbc_url
    -Map<String, String>: jdbc_connection

    +__init__(app_name: String, jdbc_url: String, jdbc_driver_path: String, user: String, password: String)
    +load_data(query: String) : DataFrame
    +transform_data(df: DataFrame) : DataFrame
    +save_data(df: DataFrame, table_name: String) : void
    +save_to_parquet(df: DataFrame, output_dir: String) : void
    +analyze_data(df: DataFrame) : void
}

SparkSession ..* MYSQLDataProcessor
MYSQLDataProcessor ..o Database

class SparkSession <<singleton>> {
    +builder : SparkSession.Builder
    +read.jdbc(url: String, table: String, properties: Map[String, String]) : DataFrame
    +write.jdbc(url: String, table: String, mode: String, properties: Map[String, String])
    +write.parquet(path: String, mode: String)
}

class Database {
    + RawData.DP_CDR_Data : Table
    + RawData.Processed_Data : Table
    + execute_query(query: String, database_name: String) : DataFrame
}

class DataTransformer {
    + transform_data(df: DataFrame) : DataFrame
}

class DataSaver {
    + save_data(df: DataFrame, table_name: String) : void
    + save_to_parquet(df: DataFrame, output_dir: String) : void
}

class DataAnalyzer {
    + analyze_data(df: DataFrame) : void
}

actor User

MYSQLDataProcessor --> DataTransformer : "Uses"
MYSQLDataProcessor --> DataSaver : "Uses"
MYSQLDataProcessor --> DataAnalyzer : "Uses"

Database --> MYSQLDataProcessor : "Provides Data"
MYSQLDataProcessor --> Database : "Writes Processed Data"

"Scripts and Configs" <-- User
"Scripts and Configs" --> MYSQLDataProcessor

artifact "Transformed Data" <<transformed>> as transformed_data
MYSQLDataProcessor --> transformed_data : "Produces"

artifact "Parquet Files" <<storage>> as parquet_files
MYSQLDataProcessor --> parquet_files : "Saves Data"

@enduml
