name: Deploy with GCP Key

on:
  pull_request:  # Trigger on pull requests (you can change to `push` if needed)
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (optional)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Adjust to your version

      # Step 3: Create the GCP key file from GitHub secret
      - name: Create GCP Key File
        run: |
          echo "${{ secrets.GCP_STORAGE_KEY }}" > GCP-Key.json
          echo "Checking if GCP-Key.json was created:"
          ls -l GCP-Key.json
          echo "Previewing first few lines of GCP-Key.json:"
          head -n 5 GCP-Key.json

      # Step 4: Export the environment variable for the key file
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/GCP-Key.json" >> $GITHUB_ENV

      # Step 5: Verify the GOOGLE_APPLICATION_CREDENTIALS variable
      - name: Verify Environment Variable
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"

      # Step 6: Run your Python script
      - name: Run Python Script
        run: python machine-learning_data-pipeline/flaskapp/DataFile/DownloadDBFile.py
