name: Setup GCP Key

on:
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  setup_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write GCP Key File
        run: |
          echo "Writing GCP-Key.json from single-line secret..."
          echo "${{ secrets.GCP_STORAGE_KEY }}" > GCP-Key.json
          echo "Created GCP-Key.json. Verifying content:"
          head -n 5 GCP-Key.json

      - name: Verify File Exists
        run: |
          echo "Checking for GCP-Key.json file:"
          ls -l GCP-Key.json

      - name: Upload GCP Key as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GCP-Key
          path: GCP-Key.json
