name: Debug GCP Key Secret

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Secret Value
        run: |
          echo "${{ secrets.GCP_STORAGE_KEY }}" | head -n 5
          echo "${{ secrets.GCP_STORAGE_KEY }}" > GCP-Key.json
          echo "Key file created. Previewing content:"
          head -n 5 GCP-Key.json
        shell: bash
