name: Setup GCP Key

on:
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  setup_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Debug the raw secret content before writing it to a file
      - name: Debug Secret Content
        run: |
          echo "Previewing raw GCP_STORAGE_KEY content:"
          printf "%s" "${{ secrets.GCP_STORAGE_KEY }}" | head -n 10

      # Write the secret to a file
      - name: Write GCP Key File
        run: |
          echo "Writing GCP-Key.json from secret..."
          printf "%s" "${{ secrets.GCP_STORAGE_KEY }}" > GCP-Key.json
          echo "Created GCP-Key.json. Verifying content:"
          head -n 5 GCP-Key.json

      # Debug the content of the generated file
      - name: Verify File Content
        run: |
          echo "Previewing GCP-Key.json content:"
          cat GCP-Key.json | head -n 10

      # Check that the file exists and show its details
      - name: Verify File Exists
        run: |
          echo "Checking for GCP-Key.json file:"
          ls -l GCP-Key.json

      # Upload the file as an artifact
      - name: Upload GCP Key as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GCP-Key
          path: GCP-Key.json
